[package]
name = "searchcar-desktop"
version = "0.1.0"
description = "SearchCar Desktop"
authors = ["SearchCar"]
edition = "2021"

[lib]
name = "searchcar_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rand = "0.9"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
url = "2"
