"""quarantine legacy identity collisions and annotate unreliable history

Revision ID: 0005
Revises: 0004
"""

from alembic import op
import sqlalchemy as sa


revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


# These pairs were recovered from the pre-integrity backup. Each source Encar
# id was incorrectly registered as an alias of the target while also existing
# as a separate canonical car. Keeping the explicit evidence makes this repair
# deterministic and auditable.
COLLISIONS = (
    ("42405959", "42404253"),
    ("42303586", "42292620"),
    ("42096205", "42093545"),
    ("42178983", "42172299"),
    ("40596115", "40586061"),
    ("42076129", "42075422"),
    ("40919983", "40917098"),
    ("42058416", "42048138"),
    ("41374663", "41368994"),
    ("42049062", "42047323"),
    ("41306879", "41306876"),
    ("41714608", "41713365"),
    ("42336033", "42335151"),
)


def _collision_values() -> str:
    return ", ".join(
        f"('{source}', '{target}')" for source, target in COLLISIONS
    )


def upgrade() -> None:
    op.add_column(
        "cars",
        sa.Column(
            "integrity_status",
            sa.String(length=30),
            nullable=False,
            server_default="VALID",
        ),
    )
    op.add_column("cars", sa.Column("integrity_reason", sa.Text(), nullable=True))
    for table in ("car_snapshots", "price_history", "car_events", "car_images"):
        op.add_column(
            table,
            sa.Column(
                "integrity_status",
                sa.String(length=30),
                nullable=False,
                server_default="VALID",
            ),
        )
        op.add_column(
            table,
            sa.Column("integrity_reason", sa.Text(), nullable=True),
        )

    connection = op.get_bind()
    pairs = _collision_values()

    # Orphaned source listings remain searchable by their own URL, but cannot
    # re-enter a project or participate in tracking.
    connection.execute(
        sa.text(
            f"""
            WITH collisions(source_id, target_id) AS (VALUES {pairs})
            UPDATE cars AS source
            SET excluded = true,
                status = 'REMOVED_FROM_SEARCH',
                integrity_status = 'QUARANTINED',
                integrity_reason =
                    'LEGACY_ALIAS_CANONICAL_COLLISION:' || target.id::text
            FROM collisions
            JOIN cars AS target
              ON target.canonical_encar_id = collisions.target_id
            WHERE source.canonical_encar_id = collisions.source_id
              AND NOT EXISTS (
                  SELECT 1
                  FROM project_cars AS active
                  WHERE active.car_id = source.id
                    AND active.tracking_enabled = true
              )
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE project_cars AS relation
            SET tracking_enabled = false,
                favorite = false,
                search_status = 'REMOVED_FROM_PROJECT'
            FROM cars AS source
            WHERE relation.car_id = source.id
              AND source.integrity_status = 'QUARANTINED'
            """
        )
    )

    # A snapshot that says it belongs to target A but was read from source B is
    # direct evidence of the old cross-listing overwrite. Preserve it for
    # audit, but exclude it from comparisons.
    connection.execute(
        sa.text(
            f"""
            WITH collisions(source_id, target_id) AS (VALUES {pairs})
            UPDATE car_snapshots AS snapshot
            SET integrity_status = 'INVALIDATED',
                integrity_reason = 'CROSS_LISTING_IDENTITY_CONFLICT'
            FROM cars AS target, collisions
            WHERE snapshot.car_id = target.id
              AND target.canonical_encar_id = collisions.target_id
              AND snapshot.payload ->> 'source_car_id' =
                  collisions.source_id
            """
        )
    )

    # Legacy material events for a conflicted target did not carry scan
    # provenance and were generated by alternating source/target snapshots.
    connection.execute(
        sa.text(
            f"""
            WITH collisions(source_id, target_id) AS (VALUES {pairs})
            UPDATE car_events AS event
            SET integrity_status = 'INVALIDATED',
                integrity_reason = 'LEGACY_IDENTITY_COMPARISON_UNTRUSTED'
            FROM cars AS target, collisions
            WHERE event.car_id = target.id
              AND target.canonical_encar_id = collisions.target_id
              AND event.kind = 'MATERIAL_UPDATE'
              AND event.payload ->> 'scan_run_id' IS NULL
            """
        )
    )

    # Report rows are JSON, so annotate rather than delete them. The API hides
    # invalidated rows and exposes their count; the original payload remains
    # recoverable in the database.
    connection.execute(
        sa.text(
            f"""
            WITH target_ids(target_id) AS (
                SELECT DISTINCT target_id
                FROM (VALUES {pairs}) AS collisions(source_id, target_id)
            )
            UPDATE scan_runs AS run
            SET payload = jsonb_set(
                run.payload::jsonb,
                '{{report}}',
                (
                    SELECT COALESCE(
                        jsonb_agg(
                            CASE
                                WHEN item ->> 'encar_id' IN (
                                    SELECT target_id FROM target_ids
                                )
                                AND item ->> 'change' IN (
                                    'MATERIAL_UPDATE',
                                    'PRICE_DROP',
                                    'PRICE_INCREASE'
                                )
                                AND (
                                    item ->> 'previous_car_id' IS NULL
                                    OR item ->> 'previous_car_id' <>
                                        item ->> 'car_id'
                                )
                                THEN item || jsonb_build_object(
                                    'integrity_status', 'INVALIDATED',
                                    'integrity_reason',
                                    'LEGACY_IDENTITY_COMPARISON_UNTRUSTED'
                                )
                                ELSE item
                            END
                            ORDER BY ordinal
                        ),
                        '[]'::jsonb
                    )
                    FROM jsonb_array_elements(
                        COALESCE(run.payload::jsonb -> 'report', '[]'::jsonb)
                    ) WITH ORDINALITY AS report_item(item, ordinal)
                ),
                true
            )
            WHERE jsonb_typeof(run.payload::jsonb -> 'report') = 'array'
            """
        )
    )


def downgrade() -> None:
    for table in ("car_images", "car_events", "price_history", "car_snapshots"):
        op.drop_column(table, "integrity_reason")
        op.drop_column(table, "integrity_status")
    op.drop_column("cars", "integrity_reason")
    op.drop_column("cars", "integrity_status")
